title: "カレンダーアプリで学ぶパッケージ開発"
summary: "
シンプルなカレンダーアプリを実際に開発しながら、Flutter パッケージ、Dart パッケージの開発の進め方を学びます。\n
\n
パッケージの開発手法を学ぶことで、自分のアイデアを基に開発したコンポーネントを世の中の開発者が再利用できるようになるだけでなく、コンポーネントの適切な役割分担を考えるきっかけになったり、またすでに公開している他のパッケージの内部実装の調べ方を理解することにもつながります。\n
\n
パッケージを開発すること自体を目的としていない方にとっても、その手法を理解することは今後アプリ開発をする上でとても役に立つ知識になるはずです。\n
\n
この本に沿ってカレンダーアプリにおけるロジック・Widget・アプリの各コンポーネントを順番に実装していくことで、パッケージ開発手法の理解の第一歩として活用してみてください。
"
topics: ["zenn", "dart", "flutter", "calendar"] # 5 つまで
published: true # 下書きは false
price: 0
chapters:
  - page1
  - page2
  - page3
  - page4
  - page5
  - page6
  - page8
  - page7
