title: "カレンダーアプリで学ぶパッケージ開発"
summary: "シンプルなカレンダーアプリを実際に開発しながら、Flutter パッケージ、Dart パッケージの開発の進め方を学びます。"
topics: ["zenn", "dart", "flutter", "calendar"] # 5 つまで
published: true # 下書きは false
price: 0
chapters:
  - page1
  - page2
  - page3
  - page4
  - page5
  - page6
  - page7
